### PR TITLE
Accordingly to Issue #5

### PR DESCRIPTION
**Pull request by Rascal**
+convert registers.h to UTF-8(registers.h line:3)

### CODE REVIEW

**Comment by martinjaeger** [comment]
Thanks for the PR. Can I close Issue #5?

**Comment by Rascal** [comment]
We need to ask @dHutchings

**Comment by dHutchings** [comment]
Sorry.  I dropped following up with you a long time ago.  I do agree that these changes fix issue #5.

I should point out that i've continued to work with the library.  I've found no other showstoppers (yet), but have added some functionality, such as not requiring an alert pin

**Comment by martinjaeger** [comment]
Cool, have you already published your improvements somewhere? Would be great to let others also benefit from it.

**Comment by dHutchings** [comment]
I'm still tracking down a bug (UV/OV protection bits don't seem to be working properly: the voltage levels aren't set correctly).  Haven't put too much time into it yet so I don't know if it's with your code / my code.

More to the point, I'm working on this in an incredibly sporadic manner.  Since I can't provide consistent feedback / updates, I figured it'd be good to do one 'deployment' once I know it's all good.

**Pull request merged**
