### PR TITLE
Implement CRC and bq76940 IC 

### PR DESCRIPTION
**Pull request by RianWardana**
- Implement CRC #2 
- Tested for bq76940 with 14 cells connected

### CODE REVIEW

**Comment by martinjaeger** [comment]
Thanks for this PR. I don't have time to review it right now, but plan to do it next week.

**Comment by rotdrop** [comment]
I have a question: is the battery current positive when _dis_charging? If it is positive during _charging_, then following change would just have the opposite effect, i.e. it woud unconditionally enable balancing during discharge when batCurrent is negative.

```
- if (abs(batCurrent) > idleCurrentThreshold) {
+ if (batCurrent > idleCurrentThreshold) {
      idleTimestamp = millis();
   }
```
The SOC-code at https://github.com/LibreSolar/bms-firmware.git makes me suspect that "-" means discharge while "+" means charge.

Am I wrong? Kind thanks

Claus

**Comment by martinjaeger** [comment]
Normally, I always use + for charging and - for discharging of batteries.

So I agree that it would probably start balancing even at high discharge currents, which doesn't make sense. Should be changed back to the absolute value, I guess... Or what do you think, @RianWardana

**Comment by KELTRONDANDD** [comment]
does not enable charge ,discharge(replay is failed)?

**Pull request merged**
